# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bw_rcpp <- function(x, sample_limit = 1000L, scale_factor = 0.5) {
    .Call(`_KDist_bw_rcpp`, x, sample_limit, scale_factor)
}

euclidean_dist_rcpp <- function(data, expo = 1) {
    .Call(`_KDist_euclidean_dist_rcpp`, data, expo)
}

gaussian_kernel_rcpp <- function(data, bw) {
    .Call(`_KDist_gaussian_kernel_rcpp`, data, bw)
}

laplacian_kernel_rcpp <- function(data, bw) {
    .Call(`_KDist_laplacian_kernel_rcpp`, data, bw)
}

polynomial_kernel_rcpp <- function(data, degree) {
    .Call(`_KDist_polynomial_kernel_rcpp`, data, degree)
}

e_dist_rcpp <- function(data, group_ = NULL) {
    .Call(`_KDist_e_dist_rcpp`, data, group_)
}

kernel_induced_distance_matrix <- function(data, g, type, group_ = NULL) {
    .Call(`_KDist_kernel_induced_distance_matrix`, data, g, type, group_)
}

hsic_cpp <- function(x, y, type = "euclidean", bw_sexp = NULL, expo = 1, scale_factor = 0.5, group_ = NULL, u_center = FALSE, is_distance = FALSE) {
    .Call(`_KDist_hsic_cpp`, x, y, type, bw_sexp, expo, scale_factor, group_, u_center, is_distance)
}

chsic_cpp <- function(D) {
    .Call(`_KDist_chsic_cpp`, D)
}

matrix_v_center <- function(A) {
    .Call(`_KDist_matrix_v_center`, A)
}

jhsic_v <- function(x, cc = 1.0, type = "euclidean", bw_sexp = NULL, expo = 1, scale_factor = 0.5, group_ = NULL) {
    .Call(`_KDist_jhsic_v`, x, cc, type, bw_sexp, expo, scale_factor, group_)
}

matrix_u_center <- function(A) {
    .Call(`_KDist_matrix_u_center`, A)
}

jhsic_u <- function(x, cc = 1.0, type = "euclidean", bw_sexp = NULL, expo = 1, scale = FALSE, scale_factor = 0.5, group_ = NULL) {
    .Call(`_KDist_jhsic_u`, x, cc, type, bw_sexp, expo, scale, scale_factor, group_)
}

rank_list <- function(x) {
    .Call(`_KDist_rank_list`, x)
}

dhsic_fast_rcpp <- function(x_list, type = "gaussian", bw = NULL, expo = 1.0, scale_factor = 0.5, group_ = NULL) {
    .Call(`_KDist_dhsic_fast_rcpp`, x_list, type, bw, expo, scale_factor, group_)
}

mhsic_cpp <- function(x, type = "euclidean", bw_sexp = NULL, expo = 1, scale_factor = 0.5) {
    .Call(`_KDist_mhsic_cpp`, x, type, bw_sexp, expo, scale_factor)
}

teststatg <- function(n1, n2, kY11, kY22, kY12, G1_11, G1_12, G2_22, G2_21, S1_1, S1_2, S2_1, S2_2) {
    .Call(`_KDist_teststatg`, n1, n2, kY11, kY22, kY12, G1_11, G1_12, G2_22, G2_21, S1_1, S1_2, S2_1, S2_2)
}

teststatl <- function(n1, n2, kY11, kY22, kY12, G1X, G2X, S1_1, S1_2, S2_1, S2_2) {
    .Call(`_KDist_teststatl`, n1, n2, kY11, kY22, kY12, G1X, G2X, S1_1, S1_2, S2_1, S2_2)
}

calculate_partial_aves_cpp <- function(full_dist, min_k = 4L, max_k = 0L) {
    .Call(`_KDist_calculate_partial_aves_cpp`, full_dist, min_k, max_k)
}

calculate_partial_aves_cross_cpp <- function(full_dist, min_k = 4L, max_k = 0L) {
    .Call(`_KDist_calculate_partial_aves_cross_cpp`, full_dist, min_k, max_k)
}

hsic_recur_cpp <- function(full_dist, min_k = 4L, max_k = 0L) {
    .Call(`_KDist_hsic_recur_cpp`, full_dist, min_k, max_k)
}

chsic_recur_cpp <- function(full_dist, min_k = 4L, max_k = 0L) {
    .Call(`_KDist_chsic_recur_cpp`, full_dist, min_k, max_k)
}

mdd_cpp <- function(x, y_sexp, type = "euclidean", bw_sexp = NULL, expo = 1, scale_factor = 0.5, group_x = NULL, u_center = FALSE, is_distance = FALSE) {
    .Call(`_KDist_mdd_cpp`, x, y_sexp, type, bw_sexp, expo, scale_factor, group_x, u_center, is_distance)
}

