# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    env:
      _R_CHECK_FORCE_SUGGESTS_: false
    strategy:
      matrix:
        r-version: ['4.1.1', 'release']
    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          brew install gcc
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          install.packages("RcppArmadillo")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
