# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    env:
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        r-version: ['4.1.1', 'release']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install system dependencies
        run: |
          brew install gcc gfortran
          echo "Installed gfortran version:"
          gfortran --version
      
      - name: Install binary packages
        run: |
          install.packages(c("remotes", "rcmdcheck", "Rcpp"))
          remotes::install_cran("RcppArmadillo", type="binary")
        shell: Rscript {0}
          
      - name: Setup R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
          needs: check
          
      - name: Check
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-build-vignettes"), error_on = "error")
        shell: Rscript {0}
